version: 0.2

phases:
  install:
    runtime-versions: 
      dotnet: latest

  build:
    commands:
      - /usr/local/bin/dotnet-install.sh --channel LTS
      - chmod +x ./deploy.sh
      - ./deploy.sh