FROM mcr.microsoft.com/dotnet/sdk:8.0 as build
WORKDIR /source
COPY ./Source /source
RUN apt update
RUN apt install -y clang zlib1g-dev
RUN dotnet publish -c release -o lambda-build /p:GenerateRuntimeConfigurationFiles=true --runtime linux-x64 Dynamo.Lambda/Dynamo.Lambda.csproj 
ENTRYPOINT [ "/bin/bash", "-l", "-c" ]

FROM public.ecr.aws/lambda/dotnet:8 as lambda
COPY --from=build /source/lambda-build ${LAMBDA_TASK_ROOT}
CMD [ "Dynamo.Lambda::Dynamo.Lambda.Function::FunctionHandler" ]