Description: This template creates one Dynamo web task definition

Parameters:
  EnvironmentName:
    Type: String
  TaskName:
    Type: String
  #Command is a comma separated list of strings. 
  Command:
    Type: String
  ExecutionRoleArn:
    Type: String
  Memory:
    Type: String
    Default: "512"
  Cpu:
    Type: String
    Default: "256"
  DesiredCount:
    Type: Number
    Default: 2
    Description: How many copies of the service task to run.    
  HealthCheckPath:
    Type: String
    Default: /health
    Description: Path to perform the healthcheck on each instance.
  HealthCheckIntervalSeconds:
    Type: Number
    Default: 5
    Description: Number of seconds to wait between each health check.
  ContainerPort:
    Type: Number
    Default: 80
    Description: The port number the application inside the docker container
      is binding to.    
  Path:
    Type: String
    Default: "*"
    Description: A path on the public load balancer that this service
      should be connected to.      

Resources:
  OneDynamoWebRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${EnvironmentName}-role-dynamo-${TaskName}"
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ecs-tasks.amazonaws.com
          Action:
          - "sts:AssumeRole"
      Policies:
      - PolicyName: !Sub "${EnvironmentName}-role-policy-${TaskName}"
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - ec2:CreateNetworkInterface
                - ec2:DeleteNetworkInterface
                - ec2:DescribeNetworkInterfaces
                - ssm:GetParameters
                - ssm:GetParameter
                - ssm:GetParametersByPath
                - secretsmanager:GetSecretValue
                - secretsmanager:DescribeSecret
                - s3:DeleteObject
                - s3:GetObject
                - s3:PutObject
                - s3:PutObjectAcl
                - s3:ListBucket
                - ses:SendEmail
                - sqs:GetQueueAttributes
                - sqs:SetQueueAttributes
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:SendMessage
                - sqs:ListQueues
                - sqs:ListQueueTags
                - sqs:GetQueueUrl
                - sns:GetTopicAttributes
                - sns:Publish
                - sns:Subscribe
                - sns:CreateTopic
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - logs:DescribeLogGroups
                - logs:DescribeLogStreams
                - cloudwatch:PutMetricData
                  # Rules which allow ECS to attach network interfaces to instances
                  # on your behalf in order for awsvpc networking mode to work right
                - 'ec2:AttachNetworkInterface'
                - 'ec2:CreateNetworkInterface'
                - 'ec2:CreateNetworkInterfacePermission'
                - 'ec2:DeleteNetworkInterface'
                - 'ec2:DeleteNetworkInterfacePermission'
                - 'ec2:Describe*'
                - 'ec2:DetachNetworkInterface'
                # Rules which allow ECS to update load balancers on your behalf
                # with the information sabout how to send traffic to your containers
                - 'elasticloadbalancing:DeregisterInstancesFromLoadBalancer'
                - 'elasticloadbalancing:DeregisterTargets'
                - 'elasticloadbalancing:Describe*'
                - 'elasticloadbalancing:RegisterInstancesWithLoadBalancer'
                - 'elasticloadbalancing:RegisterTargets'                
              Resource: "*"

  OneFfeCliTaskDefinitionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${EnvironmentName}-${TaskName}-task-log-group

  OneFfeCliTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${EnvironmentName}-ecs-task-${TaskName}
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      ExecutionRoleArn: !Ref ExecutionRoleArn
      TaskRoleArn: !GetAtt OneDynamoWebRole.Arn
      Cpu: !Sub ${Cpu}
      Memory: !Sub ${Memory}
      ContainerDefinitions:
        - Name: !Sub ${EnvironmentName}-ecs-task-container-${TaskName}
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${EnvironmentName}-dynamo-repository:latest
          Command: !Split [",", !Ref Command]
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          Environment:
            - Name: "ENVIRONMENT"
              Value: !Sub ${EnvironmentName}
            - Name: "AppSettings__EnvironmentName"
              Value: !Sub "${EnvironmentName}"
            - Name: "AppSettings__AWSRegion"
              Value: !Sub "${AWS::Region}"
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub /ecs/${EnvironmentName}-${TaskName}-task-log-group
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  Service:
    Type: AWS::ECS::Service
    DependsOn: LoadBalancerRule
    Properties:
      ServiceName: !Sub ${EnvironmentName}-ecs-task-${TaskName}-service
      Cluster: !Sub ${EnvironmentName}-dynamo-fargate-cluster
      LaunchType: FARGATE
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      DesiredCount: !Ref 'DesiredCount'
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - Fn::ImportValue: 
                !Sub ${EnvironmentName}-ECSSecurityGroup
          Subnets:
            - Fn::ImportValue:
                !Sub ${EnvironmentName}-PublicSubnet1
            - Fn::ImportValue:
                !Sub ${EnvironmentName}-PublicSubnet2
      TaskDefinition: !Ref OneFfeCliTaskDefinition
      LoadBalancers:
        - ContainerName: !Sub ${EnvironmentName}-ecs-task-container-${TaskName}
          ContainerPort: !Ref 'ContainerPort'
          TargetGroupArn: !Ref 'TargetGroup'              

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: !Ref 'HealthCheckIntervalSeconds'
      HealthCheckPath: !Ref 'HealthCheckPath'
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 4
      HealthyThresholdCount: 2
      TargetType: ip
      Name: !Sub ${EnvironmentName}-ecs-task-${TaskName}-tg
      Port: !Ref 'ContainerPort'
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      VpcId:
        Fn::ImportValue:
          !Sub ${EnvironmentName}-VPCId

  LoadBalancerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: 'forward'
      Conditions:
        - Field: path-pattern
          Values: [!Ref 'Path']
      ListenerArn:
        Fn::ImportValue:
          !Sub ${EnvironmentName}-PublicListener
      Priority: 1              

      