Description:
  This template deploys resources that should not be brought down with the root app

Parameters:
  CFTemplateBucket:
    Type: String
  EnvironmentName:
    Type: String
  ApplicationName:
    Type: String

Resources:
  ECR:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${CFTemplateBucket}/ECR/ecr.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName        

  S3:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${CFTemplateBucket}/S3/s3.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName             
        ApplicationName: !Ref ApplicationName
        CFTemplateBucket: !Ref CFTemplateBucket

  SecretsManager:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${CFTemplateBucket}/SecretsManager/secrets.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName             
