Description:
  This template deploys all resources

Parameters:
  CFTemplateBucket:
    Type: String
  EnvironmentName:
    Type: String
  ApplicationName:
    Type: String

Resources:
  Network:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${CFTemplateBucket}/Network/network.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName

  ECS:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - Network
    Properties:
      TemplateURL: !Sub https://${CFTemplateBucket}/ECS/ecs.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName        
        CFTemplateBucket: !Ref CFTemplateBucket

  CodePipelineIam:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${CFTemplateBucket}/CodePipeline/codepipeline-iam.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName        
        ApplicationName: !Ref ApplicationName

  CodePipeline:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - Network
      - ECS
      - CodePipelineIam
    Properties:
      TemplateURL: !Sub https://${CFTemplateBucket}/CodePipeline/ecs-service-pipeline.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName        
        ApplicationName: !Ref ApplicationName

  Lambda:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - Network
      - ECS
      - CodePipeline
    Properties:
      TemplateURL: !Sub https://${CFTemplateBucket}/Lambda/lambda.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName        
        ApplicationName: !Ref ApplicationName        