Description:
  This template deploys secrets for the application

Parameters:
  EnvironmentName:
    Type: String
  
Resources:
  GithubOauthSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub /${EnvironmentName}/githuboauthkey
      Description: "Secret for AWS related Secret Keys"
      SecretString: '{"githuboauthkey": "this is fake"}'